### ISSUE TITLE
[BUG] detox seems to be skipping installation of extras

### ISSUE THREAD

**Issue by webknjaz** [tox-dev/detox#14]
I tried to replace tox with detox and got `pytest` not installed.
I do `detox --notest` and then `detox`, but I also tried running `detox` on my laptop without `--notest` step and behavior is still the same: `ERROR: InvocationError for command could not find executable 'pytest'`.

- [x] Minimal reproducible example or detailed description, assign "bug"
  https://github.com/cherrypy/cheroot/commit/733a772ad5cc18bd3ba86931441818a5face0ce8
- [x] OS and `pip list` output
  Travis CI: https://travis-ci.org/cherrypy/cheroot/jobs/423594044#L1642
  (but reproducible everywhere I tried)

cc @obestwalter @gaborbernat

P.S. Moved from tox-dev/tox#957 to here as per @gaborbernat's request.

**Comment by obestwalter** [comment]
Also does not work with older versions of detox and tox, so not a regression, I think.

**Comment by gaborbernat** [comment]
per https://github.com/tox-dev/detox/issues/40 this is now out of scope
