### ISSUE TITLE
detox: Have some level of non-concurrency.

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/detox#22]
From tox created by [pytoxbot](https://github.com/pytoxbot) : tox-dev/tox#234  

- Bitbucket: https://bitbucket.org/hpk42/tox/issue/234
- Originally reported by: @schinckel
- Originally created at: 2015-04-06T12:45:57.794

I have a really nice workflow for managing coverage testing using tox: I have an envlist that looks something like:

```
clean,{py27,py33,py34,pypy}-django{17,18},status
```

The first listed environment simply removes the existing coverage data, and the final one runs the coverage status reports.

The issue is that with detox, the env `status` runs before any of the other envs have had a chance to finish.

I'd love some way of either marking that a specific env should _not_ run under detox (as it gives an error that no coverage data was found), or should run after everything else.

The only workaround I have come up with is to remove the `status` env from the envlist, and run `tox -e status` after `detox`.

**Comment by RonnyPfannschmidt** [comment]
a "stages" concept like travis would help

a "services" concept as well - both may be more suitable for core tox to begin with

**Comment by obestwalter** [comment]
Hi @RonnyPfannschmidt, that's what I think. I don't know if you noticed already, but as detox is [pretty much umnaintained](https://github.com/tox-dev/detox/issues/27), it's heading that way: https://github.com/tox-dev/tox/issues/439

**Comment by obestwalter** [comment]
Closing in favour of tox-dev/tox#439.
