### ISSUE TITLE
detox needs a maintainer (or it needs to die)

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/detox#27]
I just cloned all remaining open issues from the tox issue tracker over here, since detox has its own isse tracking now. What detox does not really have is a maintainer feeling responsible for the project. 

Since joining the tox project I kept detox on life support making some releases when necessary but I don't use detox myself and it makes no sense for me to maintain a project that I don't use. 

If anyone who uses and cares for detox wants to pick up development they would be warmly welcomed. It looks like none of the other maintainers in tox-dev are using detox either as there is [new breakage](https://github.com/tox-dev/detox/issues/15) occurring with the last tox releases that would have been caught otherwise. 

So at the moment to me it looks like the only way parallel execution orchestrated from within tox will survive if it becomes a first class citizen by implementing the functionality right into the core (be that by starting off with merging the (tiny) detox code into tox or any other way). There is an [issue already over at tox about this](https://github.com/tox-dev/tox/issues/439).

**Comment by obestwalter** [comment]
This weekend did not go as I expected. Instead of finally catching up on tox development, I found myself being sucked into whipping detox back into shape and thinking about how we can keep it afloat with reasonable effort.

For now I will just make sure that issues here get handled in reasonable time and that new versions of tox don't break compatibility with detox (by adding compatibility layers to detox or if this gets to tedious, have an harder minimum requirement for the used tox version - simplest would be to say that the current version of detox should always be run with a current version of tox).

**Comment by gaborbernat** [comment]
per https://github.com/tox-dev/detox/issues/40 this is now out of scope
