### ISSUE TITLE
Detox ignores --listenvs

### ISSUE THREAD

**Issue by relud** [tox-dev/detox#35]
it just lists all of my tests. `tox --listenvs` works fine.

Running from macOS High Sierra Version 10.13.6 (17G65) with `brew install python@2 && pip install detox`

```
$ tox --version
3.5.1 imported from /usr/local/lib/python2.7/site-packages/tox/__init__.pyc
registered plugins:
    detox-0.15 at /usr/local/lib/python2.7/site-packages/detox/tox_proclimit.pyc
$ detox --version
detox 0.15
```

**Comment by obestwalter** [comment]
Hi @relud, detox is really not that clever. All it does is passing through whatever you give it to tox, takes the config and then runs the envs in parallel:

https://github.com/tox-dev/detox/blob/9404483e526fb409e9aa4cf13b7c881e79a44d87/detox/cli.py#L16-L20

So I guess that even though tox would stop after a command like `--listenvs` detox just chugs along. So I would recommend simply not using detox for commands like this as all they do is pass through to tox.
