### ISSUE TITLE
Deprecate  the tool

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/detox#40]
https://github.com/tox-dev/tox/pull/1102 will replace this.

**Comment by obestwalter** [comment]
:+1:

**Comment by obestwalter** [comment]
Ideally we release that short before tox 3.7 is released. @gaborbernat please let me know, when you want to cut 3.7.

**Comment by gaborbernat** [comment]
Feel free to release it now, we'll probably be cutting 3.7 in an hour or two 👍 Just polishing up the PR.
